server {
    listen 80;
    server_name dns.example.net;

    location /.well-known/acme-challenge/ {
        root /var/lib/acme-challenge;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}
