// Package cachezones renders CoreDNS cache exclusions for zones served from
// the local authoritative zone directory.
package cachezones

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/miekg/dns"
)

// Render scans zoneDir and returns a CoreDNS fragment that disables positive
// and negative caching for every locally authoritative zone.
func Render(zoneDir string) ([]byte, error) {
	entries, err := filepath.Glob(filepath.Join(zoneDir, "*.zone"))
	if err != nil {
		return nil, fmt.Errorf("list zone files: %w", err)
	}
	zones := make(map[string]struct{}, len(entries))
	for _, path := range entries {
		zone, err := zoneOrigin(path)
		if err != nil {
			return nil, err
		}
		zones[zone] = struct{}{}
	}
	ordered := make([]string, 0, len(zones))
	for zone := range zones {
		ordered = append(ordered, zone)
	}
	sort.Strings(ordered)

	var output bytes.Buffer
	output.WriteString("# Generated by rill-cache-zones; do not edit.\n")
	if len(ordered) != 0 {
		fmt.Fprintf(&output, "disable success %s\n", strings.Join(ordered, " "))
		fmt.Fprintf(&output, "disable denial %s\n", strings.Join(ordered, " "))
	}
	return output.Bytes(), nil
}

func zoneOrigin(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", path, err)
	}
	// Read-only: nothing was written, so a close failure changes nothing.
	defer func() { _ = file.Close() }()
	parser := dns.NewZoneParser(bufio.NewReader(file), "", path)
	var origin string
	for rr, ok := parser.Next(); ok; rr, ok = parser.Next() {
		soa, ok := rr.(*dns.SOA)
		if !ok {
			continue
		}
		if origin != "" {
			return "", fmt.Errorf("parse %s: multiple SOA records", path)
		}
		origin = strings.ToLower(dns.Fqdn(soa.Hdr.Name))
	}
	if err := parser.Err(); err != nil {
		return "", fmt.Errorf("parse %s: %w", path, err)
	}
	if origin == "" {
		return "", fmt.Errorf("parse %s: missing SOA record", path)
	}
	return origin, nil
}

// WriteAtomic replaces path without exposing a partially written fragment.
func WriteAtomic(path string, content []byte) (err error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".cache-zones-")
	if err != nil {
		return err
	}
	temporary := file.Name()
	// Best effort: on the success path the rename has already consumed
	// this name, so the remove is expected to fail with ENOENT.
	defer func() { _ = os.Remove(temporary) }()
	if err := file.Chmod(0o640); err != nil {
		return errors.Join(err, closeError("close temporary cache zone", file.Close))
	}
	if _, err := file.Write(content); err != nil {
		return errors.Join(err, closeError("close temporary cache zone", file.Close))
	}
	if err := file.Sync(); err != nil {
		return errors.Join(err, closeError("close temporary cache zone", file.Close))
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(temporary, path)
}

// closeError runs a cleanup function and labels its failure.
func closeError(context string, closeFn func() error) error {
	if err := closeFn(); err != nil {
		return fmt.Errorf("%s: %w", context, err)
	}
	return nil
}

// closeWithError joins a cleanup failure onto a named error return without
// discarding the primary error.
func closeWithError(errp *error, context string, closeFn func() error) {
	*errp = errors.Join(*errp, closeError(context, closeFn))
}
