// blocklist-merge compiles domain lists and hosts files into a deterministic
// hosts file consumable by CoreDNS's hosts plugin.
package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const maxLineBytes = 1 << 20

func main() {
	var output string
	var allow string
	flag.StringVar(&output, "output", "", "output hosts file")
	flag.StringVar(&allow, "allow", "", "optional allowlist file")
	flag.Parse()

	if output == "" || flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: blocklist-merge -output FILE [-allow FILE] INPUT...")
		os.Exit(2)
	}

	blocked, err := readFiles(flag.Args())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if allow != "" {
		allowed, err := readFiles([]string{allow})
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		for domain := range allowed {
			delete(blocked, domain)
		}
	}

	if err := writeAtomic(output, blocked); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %d blocked domains to %s\n", len(blocked), output)
}

func readFiles(paths []string) (map[string]struct{}, error) {
	domains := make(map[string]struct{})
	for _, path := range paths {
		file, err := os.Open(path)
		if err != nil {
			return nil, fmt.Errorf("open %s: %w", path, err)
		}
		err = readDomains(file, domains)
		closeErr := file.Close()
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		if closeErr != nil {
			return nil, fmt.Errorf("close %s: %w", path, closeErr)
		}
	}
	return domains, nil
}

func readDomains(reader io.Reader, domains map[string]struct{}) error {
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 64*1024), maxLineBytes)
	for scanner.Scan() {
		line := strings.TrimSpace(strings.SplitN(scanner.Text(), "#", 2)[0])
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		start := 0
		if net.ParseIP(strings.Trim(fields[0], "[]")) != nil {
			start = 1
		}
		for _, field := range fields[start:] {
			domain, ok := normalizeDomain(field)
			if ok {
				domains[domain] = struct{}{}
			}
		}
	}
	return scanner.Err()
}

func normalizeDomain(value string) (string, bool) {
	domain := strings.ToLower(strings.TrimSuffix(strings.TrimSpace(value), "."))
	if domain == "" || domain == "localhost" || len(domain) > 253 || net.ParseIP(domain) != nil {
		return "", false
	}
	labels := strings.Split(domain, ".")
	if len(labels) < 2 {
		return "", false
	}
	for _, label := range labels {
		if len(label) == 0 || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
			return "", false
		}
		for _, char := range label {
			if (char < 'a' || char > 'z') && (char < '0' || char > '9') && char != '-' && char != '_' {
				return "", false
			}
		}
	}
	return domain, true
}

func writeAtomic(path string, domains map[string]struct{}) error {
	if len(domains) == 0 {
		return errors.New("refusing to publish an empty blocklist")
	}
	ordered := make([]string, 0, len(domains))
	for domain := range domains {
		ordered = append(ordered, domain)
	}
	sort.Strings(ordered)

	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, filepath.Base(path)+".tmp-")
	if err != nil {
		return fmt.Errorf("create temporary output: %w", err)
	}
	temporaryPath := temporary.Name()
	removeTemporary := true
	defer func() {
		if removeTemporary {
			_ = os.Remove(temporaryPath)
		}
	}()

	buffer := bufio.NewWriter(temporary)
	if _, err := fmt.Fprintln(buffer, "# Generated by rilldns blocklist-merge; do not edit."); err != nil {
		_ = temporary.Close()
		return err
	}
	for _, domain := range ordered {
		if _, err := fmt.Fprintf(buffer, "0.0.0.0 %s\n", domain); err != nil {
			_ = temporary.Close()
			return err
		}
	}
	if err := buffer.Flush(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("publish output: %w", err)
	}
	removeTemporary = false
	return nil
}
